=== LuFi16/Bazar/bazarSchema.xsd
<?xml version="1.0"?>
<!-- Odkaz na github: https://github.com/LuFi16/Bazar -->
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">
    <xs:element name="Bazar">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="general_settings"> <!-- General settings -->       
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="charset" name="charset"/>
                            <xs:element type="language" name="language"/>
                            <xs:element type="on-off" name="javascript"/>
                            <xs:element type="on-off" name="vbscript"/>
                            <xs:element name="function">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="on-off" name="searching"/>
                                        <xs:element type="on-off" name="filters"/>
                                        <xs:element type="on-off" name="check_boxes"/>
                                        <xs:element type="on-off" name="popup_window"/>
                                        <xs:element type="on-off" name="advertisement"/>
                                        <xs:element type="on-off" name="help"/>
                                        <xs:element type="on-off" name="scroll_bar"/>
                                        <xs:element type="on-off" name="video"/>
                                        <xs:element type="on-off" name="chat"/>
                                        <xs:element type="on-off" name="forum"/>
                                        <xs:element type="on-off" name="zoom"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="protocol" name="protocol"/>
                            <xs:element type="xs:string" name="access_restrictions"/>
                            <xs:element type="email" name="contact"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="overwiev_of_rights"> <!-- Settings of user rights --> 
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="right" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="symbol" name="symbol"/>
                                        <xs:element type="on-off" name="read"/>
                                        <xs:element type="on-off" name="users_editing"/>
                                        <xs:element type="on-off" name="draft_ad"/>
                                        <xs:element type="on-off" name="ad_accept"/>
                                        <xs:element type="on-off" name="delete_ad"/>
                                        <xs:element type="on-off" name="responses_to_ad"/>
                                        <xs:element type="on-off" name="accept_responses"/>
                                        <xs:element type="on-off" name="decline_responses"/>
                                        <xs:element type="on-off" name="reset_passwords"/>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="role" use="required"/>
                                    <xs:attribute type="xs:integer" name="num" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="category" maxOccurs="unbounded" minOccurs="0"> <!-- Each category --> 
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:integer" name="number_of_ad_on_page"/>
                            <xs:element type="desc" name="description"/>
                            <xs:element name="access_rights">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="person" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="name"/>
                                                    <xs:element type="xs:string" name="surname"/>
                                                    <xs:element type="xs:string" name="login"/>
                                                    <xs:element type="symbol" name="rights"/>
                                                    <xs:element type="xs:string" name="email"/>
                                                    <xs:element type="xs:string" name="phone"/>
                                                    <xs:element name="adress">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element type="xs:string" name="street"/>
                                                                <xs:element type="xs:string" name="land_registry_number"/>
                                                                <xs:element type="xs:string" name="house_number"/>
                                                                <xs:element type="xs:string" name="city"/>
                                                                <xs:element type="xs:string" name="ZIP"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>                                                   
                                                </xs:sequence>
                                                <xs:attribute type="xs:byte" name="id" use="required"/>
                                                <xs:attribute type="xs:string" name="gendre" use="required"/>
                                                <xs:attribute type="xs:string" name="state" use="required"/>
                                                <xs:attribute type="xs:string" name="age" use="required"/>
                                                <xs:attribute type="xs:string" name="browser" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="type" use="required"/>
                        <xs:attribute type="xs:string" name="shortcut" use="required"/>
                        <xs:attribute type="xs:string" name="sale" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- Restriction settings -->
    <xs:simpleType name="on-off">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="1"/>
        </xs:restriction>
    </xs:simpleType> 
    <xs:simpleType name="charset">
        <xs:restriction base="xs:string">
            <xs:enumeration value="utf-8"/>
            <xs:enumeration value="windows-1258"/>
            <xs:enumeration value="utf-7"/>
            <xs:enumeration value="iso-8859"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="language">
        <xs:restriction base="xs:string">
            <xs:enumeration value="cestina"/>
            <xs:enumeration value="anglictina"/>
            <xs:enumeration value="nemcina"/>
            <xs:enumeration value="francouzstina"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="protocol">
        <xs:restriction base="xs:string">
            <xs:enumeration value="http"/>
            <xs:enumeration value="https"/>
            <xs:enumeration value="ftp"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="symbol">
        <xs:restriction base="xs:string">
            <xs:enumeration value="A"/>
            <xs:enumeration value="S"/>
            <xs:enumeration value="R"/>
            <xs:enumeration value="N"/>
        </xs:restriction>
    </xs:simpleType> 
    <xs:simpleType name="email">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^@]+@[^\.]+\..+"/> <!-- Recognition of email adress -->
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="desc">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="150"/>
        </xs:restriction>
    </xs:simpleType> 
</xs:schema>

=== LuFi16/Bazar/Bazar.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="fiedlerova_lucie.xsl"?>
<!-- Odkaz na github: https://github.com/LuFi16/Bazar -->
<Bazar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="bazarSchema.xsd">
    <!-- General settings -->
    <general_settings>
        <charset>utf-8</charset>
        <language>cestina</language>
        <javascript>1</javascript>
        <vbscript>0</vbscript>
        <function>
            <searching>1</searching>
            <filters>1</filters>
            <check_boxes>0</check_boxes>
            <popup_window>0</popup_window>
            <advertisement>1</advertisement>
            <help>1</help>
            <scroll_bar>1</scroll_bar>
            <video>0</video>
            <chat>0</chat>  
            <forum>0</forum>  
            <zoom>1</zoom>             
        </function>
        <protocol>http</protocol>
        <access_restrictions></access_restrictions>	
        <contact>bazar@bazar.cz</contact>
    </general_settings>

    <!-- Settings of user rights -->
    <overwiev_of_rights>
        <right role="Administrátor" num="1">
            <symbol>A</symbol>
            <read>1</read>
            <users_editing>1</users_editing>
            <draft_ad>1</draft_ad>
            <ad_accept>1</ad_accept>
            <delete_ad>1</delete_ad>
            <responses_to_ad>1</responses_to_ad>
            <accept_responses>1</accept_responses>
            <decline_responses>1</decline_responses>
            <reset_passwords>1</reset_passwords>
        </right>
        <right role="Správce inzerátů" num="2">
            <symbol>S</symbol>
            <read>1</read>
            <users_editing>0</users_editing>
            <draft_ad>1</draft_ad>
            <ad_accept>1</ad_accept>
            <delete_ad>1</delete_ad>
            <responses_to_ad>1</responses_to_ad>
            <accept_responses>1</accept_responses>
            <decline_responses>1</decline_responses>
            <reset_passwords>0</reset_passwords>
        </right>
        <right role="Registrovaný uživatel" num="3">
            <symbol>R</symbol>	
            <read>1</read>
            <users_editing>0</users_editing>
            <draft_ad>1</draft_ad>
            <ad_accept>0</ad_accept>
            <delete_ad>0</delete_ad>
            <responses_to_ad>1</responses_to_ad>
            <accept_responses>1</accept_responses>
            <decline_responses>1</decline_responses>
            <reset_passwords>0</reset_passwords>
        </right>
        <right role="Neregistrovaný uživatel" num="4">
            <symbol>N</symbol>	
            <read>1</read>
            <users_editing>0</users_editing>
            <draft_ad>0</draft_ad>
            <ad_accept>0</ad_accept>
            <delete_ad>0</delete_ad>
            <responses_to_ad>0</responses_to_ad>
            <accept_responses>0</accept_responses>
            <decline_responses>0</decline_responses>
            <reset_passwords>0</reset_passwords>
        </right>
    </overwiev_of_rights>

    <!-- Each category -->
    <category type="Osobní" shortcut="M1" sale="best">
        <number_of_ad_on_page>15</number_of_ad_on_page>
        <description>Auta se čtyřmi koly sloužící pro přepravu osob (M).</description>
        <access_rights>
            <person id="1" gendre="male" state="CZ" age="35" browser="Chrome">
                <name>Karel</name>
                <surname>Králík</surname>
                <login>KaKra</login>
                <rights>A</rights>
                <email>Kralik@gmail.cz</email>
                <phone>756 162 175</phone>
                <adress>
                    <street>Krátká</street>
                    <land_registry_number>32</land_registry_number>
                    <house_number>78</house_number>
                    <city>Praha</city>
                    <ZIP>27501</ZIP>
                </adress>
            </person>
            <person id="2" gendre="female" state="CZ" age="27" browser="Chrome">
                <name>Eva</name>
                <surname>Hořejši</surname>
                <login>evicka25</login>
                <rights>S</rights>
                <email>evicka@volny.cz</email>
                <phone>542 878 775</phone>
                <adress>
                    <street>Komenského</street>
                    <land_registry_number>75</land_registry_number>
                    <house_number>123</house_number>
                    <city>Plzeň</city>
                    <ZIP>27805</ZIP>
                </adress>
            </person>
            <person id="3" gendre="male" state="CZ" age="43" browser="Opera">
                <name>Jan</name>
                <surname>Dolní</surname>
                <login>Dolajn</login>
                <rights>R</rights>
                <email>dalajn@volny.cz</email>
                <phone>752 128 712</phone>
                <adress>
                    <street>Amatérů</street>
                    <land_registry_number>86</land_registry_number>
                    <house_number>678</house_number>
                    <city>Plzeň</city>
                    <ZIP>27802</ZIP>
                </adress>
            </person>
            <person id="4" gendre="male" state="CZ" age="52" browser="Firefox">
                <name>Evžen</name>
                <surname>Polák</surname>
                <login>Ev7a</login>
                <rights>R</rights>
                <email>polake@volny.cz</email>
                <phone>442 728 715</phone>
                <adress>
                    <street>Plzeňská</street>
                    <land_registry_number>23</land_registry_number>
                    <house_number>945</house_number>
                    <city>Olomouc</city>
                    <ZIP>22402</ZIP>
                </adress>
            </person>
            <person id="5" gendre="?" state="?" age="?" browser="?">
                <name>Neregistrovaný</name>
                <surname></surname>
                <login>host</login>
                <rights>N</rights>
                <email></email>
                <phone></phone>
                <adress>
                    <street></street>
                    <land_registry_number></land_registry_number>
                    <house_number></house_number>
                    <city></city>
                    <ZIP></ZIP>
                </adress>
            </person>
        </access_rights>
    </category>

    <category type="Užitková" shortcut="M2" sale="medium">
        <number_of_ad_on_page>15</number_of_ad_on_page>
        <description>Auta se čtyřmi koly sloužící k přepravě osob i nákladu (M).</description>
        <access_rights>
            <person id="1" gendre="male" state="CZ" age="35" browser="Chrome">
                <name>Karel</name>
                <surname>Králík</surname>
                <login>KaKra</login>
                <rights>A</rights>
                <email>Kralik@gmail.cz</email>
                <phone>756 162 175</phone>
                <adress>
                    <street>Krátká</street>
                    <land_registry_number>32</land_registry_number>
                    <house_number>78</house_number>
                    <city>Praha</city>
                    <ZIP>27501</ZIP>
                </adress>
            </person>
            <person id="2" gendre="female" state="CZ" age="27" browser="Chrome">
                <name>Eva</name>
                <surname>Hořejši</surname>
                <login>evicka25</login>
                <rights>S</rights>
                <email>evicka@volny.cz</email>
                <phone>542 878 775</phone>
                <adress>
                    <street>Komenského</street>
                    <land_registry_number>75</land_registry_number>
                    <house_number>123</house_number>
                    <city>Plzeň</city>
                    <ZIP>27805</ZIP>
                </adress>
            </person>
            <person id="3" gendre="male" state="CZ" age="50" browser="Firefox">
                <name>Pavel</name>
                <surname>Adam</surname>
                <login>Ada12adA</login>
                <rights>R</rights>
                <email>P.Adam@seznam.cz</email>
                <phone>357 162 185</phone>
                <adress>
                    <street>Dlouhá</street>
                    <land_registry_number>52</land_registry_number>
                    <house_number>148</house_number>
                    <city>Praha</city>
                    <ZIP>27501</ZIP>
                </adress>
            </person>
            <person id="4" gendre="female" state="CZ" age="19" browser="Opera">
                <name>Patricie</name>
                <surname>Lišková</surname>
                <login>Listicka</login>
                <rights>R</rights>
                <email>pajaliska@seznam.cz</email>
                <phone>387 615 942</phone>
                <adress>
                    <street>Konečná</street>
                    <land_registry_number>12</land_registry_number>
                    <house_number>854</house_number>
                    <city>Těšín</city>
                    <ZIP>27403</ZIP>
                </adress>
            </person>
            <person id="5" gendre="?" state="?" age="?" browser="?">
                <name>Neregistrovaný</name>
                <surname></surname>
                <login>host</login>
                <rights>N</rights>
                <email></email>
                <phone></phone>
                <adress>
                    <street></street>
                    <land_registry_number></land_registry_number>
                    <house_number></house_number>
                    <city></city>
                    <ZIP></ZIP>
                </adress>
            </person>
        </access_rights>
    </category>
    
    <category type="Nákladní" shortcut="N" sale="low">
        <number_of_ad_on_page>15</number_of_ad_on_page>
